### PR TITLE
[WIP] Change MemoWise public API

### PR DESCRIPTION
**Pull request by paracycle**
Re-attempt at #213 with @jemmaissroff, still a WIP...

**Before merging:**

- [ ] Copy the table printed at the end of the latest benchmark results into the `README.md` and update this PR
- [ ] If this change merits an update to `CHANGELOG.md`, add an entry following Keep a Changelog [guidelines](https://keepachangelog.com/en/1.0.0/) with [semantic versioning](https://semver.org/)

### CODE REVIEW

**Comment by PikachuEXE** [comment]
Should I wait for this to be finished before migrating to this gem?

**Comment by paracycle** [comment]
> Should I wait for this to be finished before migrating to this gem?

I am not a maintainer of the gem, so I am not sure if this will ever get merged and released. But, my aim is to keep the public API surface change to only the change from `prepend MemoWise` to `extend MemoWise`. So, if you adopt now, it shouldn't be hard to upgrade later.

**Comment by ms-ati** [comment]
Hi @PikachuEXE, my understanding is that this is intended to be a proposal to be discussed -- which is awesome! -- but at this time, there's no current understanding nor expectation that this proposed API change will be accepted, is there?

UPDATE @paracycle I see your response first, and 👍🏻 to how you expressed it!

**Comment by PikachuEXE** [comment]
OK I get this is a proposal now

I would ask
> 1. Is there anything would be taken away (including the potential benefits) by moving away from `prepend`?
> 2. How this gem's compatibility with other gems (which also use meta programming, e.g. [contracts.ruby](https://github.com/egonSchiele/contracts.ruby)) would be comparing `prepend` and `extend`?
> 3. Is there any other not so obvious potential issues that we can think of?
> 4. What are the original intents by picking `prepend` over `extend`/`include`?

**Comment by paracycle** [comment]
@PikachuEXE all of those points will be addressed in the PR description in detail once the build gets green on this branch.

**Comment by PikachuEXE** [comment]
> This branch has conflicts that must be resolved

**Comment by paracycle** [comment]
> > This branch has conflicts that must be resolved
> 
> 

Yes! That's why the PR is marked [WIP] and is set as Draft.

**Comment by jemmaissroff** [comment]
Closed and replaced by #253

**Pull request closed without merging**
